@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50X2lkIjoxLCJleHAiOjE2NDY5NjQ5NDl9.Jf2z3rcXSjVNq4VJmanWh7oDvc-50zaiPTnRIIuAeKI
###Create new user
POST http://localhost:3000/students
Content-Type: application/json

{ 
    "first_name": "Test",
      "last_name": "test",
      "email": "Test",
      "password": "Test",
      "phone_number" : "Test",
      "short_bio" : "Test",
      "linkedin_url" : "Test",
      "twitter_handle" : "Test",
      "personal_blog_url" : "Test",
      "resume_url" : "Test",
      "github_url" : "Test",
      "photo_url" : "Test"
}

### Show student
GET http://localhost:3000/students
Content-Type: application/json

### Update 
PATCH http://localhost:3000/students/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "first_name": "Calum"
}

### DELETE Student
DELETE http://localhost:3000/students/5
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Users create (signup)
POST http://localhost:3000/students
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "cramsel@test.com",
  "password": "password"
}   
